KonsiLoja/Models/Contrato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KonsiLoja.Models
{
    public class Contrato
    {
        public int ContratoId { get; set; }
        [DisplayName("Número do contrato")]
        [RegularExpression("(\\d{0,10})", ErrorMessage = "O Número de contrato precisa de 10 digitos")]
        public int NumeroContrato { get; set; }
        [DisplayName("Valor do contrato")]
        public decimal ValorContrato { get; set; }
        [DisplayName("Saldo Devedor")]
        public decimal SaldoDevedor { get; set; }
        [DisplayName("Parcelas Totais")]
        public int ParcelasTotais { get; set; }
        [DisplayName("Parcelas Pagas")]
        public int ParcelasPagas { get; set; }
        [DisplayName("Valor de Parcelas")]
        public int ValorParcela { get; set; }
        public Vendedor Vendedores { get; set; }
        public int ? VendedoresId { get; set; }
        public Cliente Clientes { get; set; }
        public int ? ClientesId { get; set; }
        




    }
}

KonsiLoja/Controllers/ContratosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KonsiLoja.Contexto;
using KonsiLoja.Models;

namespace KonsiLoja.Controllers
{
    public class ContratosController : Controller
    {
        private readonly KonsiContexto _context;

        public ContratosController(KonsiContexto context)
        {
            _context = context;
        }

        // GET: Contratos
        public  IActionResult Index( decimal ? devedor , decimal ? parcelasPagas, int ? CPF)
        {
            var ListaPesquisa = _context.Contratos.Where(  x => x.NumeroContrato > 0 || x.ParcelasPagas < 0 || x.SaldoDevedor > 0 || x.Clientes.CPF == CPF ).ToList();

            return View(ListaPesquisa); ;
        }

        // GET: Contratos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contrato = await _context.Contratos
                .Include(c => c.Clientes)
                .Include(c => c.Vendedores)
                .FirstOrDefaultAsync(m => m.ContratoId == id);
            if (contrato == null)
            {
                return NotFound();
            }

            return View(contrato);
        }

        // GET: Contratos/Create
        public IActionResult Create()
        {
            ViewBag.CPF = new SelectList(_context.Clientes, "ClienteId", "CPF");
            ViewData["ClientesId"] = new SelectList(_context.Clientes, "ClienteId", "Nome");
            ViewData["VendedoresId"] = new SelectList(_context.Vendedors, "VendedorId", "Nome");
            return View();
        }

        // POST: Contratos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ContratoId,NumeroContrato,ValorContrato,SaldoDevedor,ParcelasTotais,ParcelasPagas,ValorParcela,VendedoresId,ClientesId,CPF,ClienteId.CPF")] Contrato contrato)
        {


            var numero = _context.Clientes.ToList();

            foreach( var item in numero)
            {

                var resultado = _context.Clientes.Where(x => x.ClienteId == item.ClienteId).Count();
                
                if(resultado > 0)
                {
                    ViewBag.Alerta = "Conteudo";
                    return View();
                }

            }


            if (ModelState.IsValid)
            {
                _context.Add(contrato);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.CPF = new SelectList(_context.Clientes, "ClienteId", "CPF", contrato.ClientesId);
            ViewBag.ClientesId = new SelectList(_context.Clientes, "ClienteId", "Nome", contrato.ClientesId);
            ViewBag.VendedoresId = new SelectList(_context.Vendedors, "VendedorId", "Nome", contrato.VendedoresId);
            return View(contrato);
        }

        // GET: Contratos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contrato = await _context.Contratos.FindAsync(id);
            if (contrato == null)
            {
                return NotFound();
            }
            ViewData["ClientesId"] = new SelectList(_context.Clientes, "ClienteId", "CPF", contrato.ClientesId);
            ViewData["VendedoresId"] = new SelectList(_context.Vendedors, "VendedorId", "Nome", contrato.VendedoresId);
            return View(contrato);
        }

        // POST: Contratos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContratoId,NumeroContrato,ValorContrato,SaldoDevedor,ParcelasTotais,ParcelasPagas,ValorParcela,VendedoresId,ClientesId")] Contrato contrato)
        {
            if (id != contrato.ContratoId)
            {
                return NotFound();
            }



            var numero = _context.Clientes.ToList();

            foreach (var item in numero)
            {

                var resultado = _context.Clientes.Where(x => x.ClienteId == item.ClienteId).Count();

                if (resultado > 0)
                {
                    ViewBag.Alerta = "Conteudo";
                    return View();
                }

            }


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contrato);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContratoExists(contrato.ContratoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientesId"] = new SelectList(_context.Clientes, "ClienteId", "ClienteId", contrato.ClientesId);
            ViewData["VendedoresId"] = new SelectList(_context.Vendedors, "VendedorId", "VendedorId", contrato.VendedoresId);
            return View(contrato);
        }

        // GET: Contratos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contrato = await _context.Contratos
                .Include(c => c.Clientes)
                .Include(c => c.Vendedores)
                .FirstOrDefaultAsync(m => m.ContratoId == id);
            if (contrato == null)
            {
                return NotFound();
            }

            return View(contrato);
        }

        // POST: Contratos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contrato = await _context.Contratos.FindAsync(id);
            _context.Contratos.Remove(contrato);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContratoExists(int id)
        {
            return _context.Contratos.Any(e => e.ContratoId == id);
        }
    }
}

KonsiLoja/Views/Contratos/Create.cshtml
@model KonsiLoja.Models.Contrato




<div class="Centro">

    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>


        <div style="text-align:center;"> <h2> Cadastro de clientes </h2></div>

        @*<div class="form-group">
                @Html.Label("Nome", "Preencha com o nome do Cliente", new { @class = "col-form-label" })
                @Html.DropDownListFor(model => model.ClientesId, (SelectList)ViewBag.ClientesId, string.Empty, new { @class = "form-control", @placeholder = "Selecione o nome do cliente", @style = "width:400px;" })
                <div class="alert-danger">
                    @Html.ValidationMessageFor(model => model.ClientesId)
                </div>
            </div>*@

        <div class="form-group">
            @Html.Label("CPF", "Preencha com o CPF do Cliente ", new { @class = "col-form-label" })
            @Html.DropDownListFor(model => model.ClientesId, (SelectList)ViewBag.CPF, string.Empty, new { @class = "form-control", @placeholder = "Selecione o CPF do Cliente", @style = "width:400px;" })
            <div class="alert-danger">
                @Html.ValidationMessageFor(model => model.ClientesId)
            </div>
        </div>



        <div class="form-group  ">
            @Html.LabelFor(model => model.NumeroContrato, new { @class = "col-form-label" })
            @Html.TextBoxFor(model => model.NumeroContrato, new { @class = "form-control", @placeholder = "Digite aqui o número do contrato", @style = "width:400px;" })
            <div class="alert-danger">
                @Html.ValidationMessageFor(model => model.NumeroContrato)
            </div>
        </div>

        <div class="form-group  ">
            @Html.LabelFor(model => model.ValorContrato, new { @class = "col-form-label" })
            @Html.TextBoxFor(model => model.ValorContrato, new { @class = "form-control", @placeholder = "Digite aqui o valor do contrato", @style = "width:400px;" })
            <div class="alert-danger">
                @Html.ValidationMessageFor(model => model.ValorContrato)
            </div>
        </div>


        <div class="form-group  ">
            @Html.LabelFor(model => model.SaldoDevedor, new { @class = "col-form-label" })
            @Html.TextBoxFor(model => model.SaldoDevedor, new { @class = "form-control", @placeholder = "Digite aqui o saldo devedor", @style = "width:400px;" })
            <div class="alert-danger">
                @Html.ValidationMessageFor(model => model.SaldoDevedor)
            </div>
        </div>

        <div class="form-group  ">
            @Html.LabelFor(model => model.ParcelasTotais, new { @class = "col-form-label" })
            @Html.TextBoxFor(model => model.ParcelasTotais, new { @class = "form-control", @placeholder = "Digite aqui o valor total das parcelas", @style = "width:400px;" })
            <div class="alert-danger">
                @Html.ValidationMessageFor(model => model.ParcelasTotais)
            </div>
        </div>

        <div class="form-group  ">
            @Html.LabelFor(model => model.ParcelasPagas, new { @class = "col-form-label" })
            @Html.TextBoxFor(model => model.ParcelasPagas, new { @class = "form-control", @placeholder = "Digite aqui o valor de parcelas pagas", @style = "width:400px;" })
            <div class="alert-danger">
                @Html.ValidationMessageFor(model => model.ParcelasPagas)
            </div>
        </div>

        <div class="form-group  ">
            @Html.LabelFor(model => model.ValorParcela, new { @class = "col-form-label" })
            @Html.TextBoxFor(model => model.ValorParcela, new { @class = "form-control", @placeholder = "Digite aqui o valor da parcela", @style = "width:400px;" })
            <div class="alert-danger">
                @Html.ValidationMessageFor(model => model.ValorParcela)
            </div>
        </div>


        @*<div class="form-group  ">
                @Html.LabelFor(model => model.VendedoresId, new { @class = "col-form-label" })
                @Html.TextBoxFor(model => model.VendedoresId, new { @class = "form-control", @placeholder = "Digite seu nome", @style = "width:400px;" })
                <div class="alert-danger">
                    @Html.ValidationMessageFor(model => model.VendedoresId)
                </div>
            </div>*@


        <div class="Centro">
            <input type="submit" value="Cadastrar o cliente" class="btn btn-dark" />
        </div>
    </form>
</div>

<style>

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }


    body {
        background-color: #FFFFFF;
        color: #535353;
        font-family: Arial, Helvetica, sans-serif;
    }

    .Centro {
        display: flex;
        justify-content: center;
    }
</style>





@if (ViewBag.Alerta == true)
{

    <div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Este cliente já possui um vendedor.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>



}







@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KonsiLoja/Views/Contratos/Delete.cshtml
@model KonsiLoja.Models.Contrato

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contrato</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroContrato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroContrato)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorContrato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorContrato)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SaldoDevedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SaldoDevedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParcelasTotais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParcelasTotais)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParcelasPagas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParcelasPagas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorParcela)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorParcela)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vendedores)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vendedores.VendedorId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clientes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clientes.ClienteId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ContratoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KonsiLoja/Views/Contratos/Details.cshtml
@model KonsiLoja.Models.Contrato

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Contrato</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroContrato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroContrato)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorContrato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorContrato)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SaldoDevedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SaldoDevedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParcelasTotais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParcelasTotais)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParcelasPagas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParcelasPagas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorParcela)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorParcela)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vendedores)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vendedores.VendedorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clientes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clientes.ClienteId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ContratoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

KonsiLoja/Views/Contratos/Edit.cshtml
@model KonsiLoja.Models.Contrato

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Contrato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContratoId" />
            <div class="form-group">
                <label asp-for="NumeroContrato" class="control-label"></label>
                <input asp-for="NumeroContrato" class="form-control" />
                <span asp-validation-for="NumeroContrato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorContrato" class="control-label"></label>
                <input asp-for="ValorContrato" class="form-control" />
                <span asp-validation-for="ValorContrato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SaldoDevedor" class="control-label"></label>
                <input asp-for="SaldoDevedor" class="form-control" />
                <span asp-validation-for="SaldoDevedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParcelasTotais" class="control-label"></label>
                <input asp-for="ParcelasTotais" class="form-control" />
                <span asp-validation-for="ParcelasTotais" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParcelasPagas" class="control-label"></label>
                <input asp-for="ParcelasPagas" class="form-control" />
                <span asp-validation-for="ParcelasPagas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorParcela" class="control-label"></label>
                <input asp-for="ValorParcela" class="form-control" />
                <span asp-validation-for="ValorParcela" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VendedoresId" class="control-label"></label>
                <select asp-for="VendedoresId" class="form-control" asp-items="ViewBag.VendedoresId"></select>
                <span asp-validation-for="VendedoresId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientesId" class="control-label"></label>
                <select asp-for="ClientesId" class="form-control" asp-items="ViewBag.ClientesId"></select>
                <span asp-validation-for="ClientesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

@if (ViewBag.Alerta == true)
{

    <div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Este cliente já possui um vendedor.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>



}

KonsiLoja/Views/Contratos/Index.cshtml
@model IEnumerable<KonsiLoja.Models.Contrato>

@{
    
}





<div class="top"> <h1> Lista de Contratos</h1></div>


<div class="busca panel-body">
    
    @using (Html.BeginForm("Index", "Contratos"))
    {
    <form class="navbar-form navbar-right" role="search">

        <div>


            <div class="col-sm-2" style="display:inline-block">
                <label> Buscar por saldo devedor : </label>
                @Html.TextBox("CPF", null, new { @class = "form-control" })
            </div>
            <div class="col-sm-2" style="display:inline-block">
                <label> Buscar por saldo devedor : </label>
                @Html.TextBox("devedor", null, new { @class = "form-control" })
            </div>

            <div class="col-sm-2" style="display:inline-block">
                <label> Buscar por número de parcelas pagas : </label>
                @Html.TextBox("parcelasPagas", null, new { @class = "form-control" })
            </div>
            <button type="submit" class="btn btn-dark">Pesquisar</button>
        </div>
    </form>
    }

</div>


<table class="table table-b">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumeroContrato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorContrato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SaldoDevedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ParcelasTotais)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ParcelasPagas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorParcela)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Clientes.CPF)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroContrato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorContrato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SaldoDevedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParcelasTotais)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParcelasPagas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorParcela)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Clientes.CPF)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.ContratoId">Editar contrato</a> |
                <a asp-action="Details" asp-route-id="@item.ContratoId">Detalhes Do Contrato</a> |
                <a asp-action="Delete" asp-route-id="@item.ContratoId">Delete</a>
            </td>
        </tr>
        }
    </tbody>

    
</table>

<style>
    .busca{
       margin: 0 auto;
    }

    .top{
        display:flex;
        justify-content:center;
        padding-bottom:40px;
    }
</style>